<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArbitrageProspectiveRepository extends EntityRepository
{
  public function getBestMarket(\Datetime $begin, \Datetime $end)
  {
    $sql = "
            SELECT                 
                market, sum(gain_1000) as sum, avg(gain_percent) as gain_percent
                FROM arbitrage_prospective
                WHERE 
                datetime >= :begin
                AND datetime <= :end
                GROUP BY market
                ORDER BY sum DESC
        ";

         //End date must be one day higher for the query to be valid
        $end = clone $end;
        $end->modify('+1 days'); 

        $stmt = $this->_em->getConnection()->prepare($sql);
        $stmt->bindValue(':begin', $begin->format('Y-m-d'));
        $stmt->bindValue(':end', $end->format('Y-m-d'));
        $stmt->execute();

        return $stmt->fetchAll();
  }
}

?>