<?php

namespace AppBundle\Entity;

/**
 * WalletDepositRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WalletDepositRepository extends \Doctrine\ORM\EntityRepository
{
}
